# Generated by Django 6.1 on 2026-08-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['id']},
        ),
    ]
