# Generated by Django 6.1 on 2026-08-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id']},
        ),
    ]
