services:
  - type: web
    name: ims-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    postDeployCommand: "./create_superuser.sh"
    startCommand: "sh -c 'python manage.py migrate && gunicorn ims.wsgi:application --bind 0.0.0.0:$PORT'"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER
        value: "true"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "true"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ims-db
          property: connectionString

databases:
  - name: ims-db
    plan: free
