# Generated by Django 6.1 on 2026-08-26 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_product_selling_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('shop', 'Shop'), ('godown', 'Godown'), ('virtual', 'Virtual'), ('shelf', 'Shelf'), ('rack', 'Rack'), ('bin', 'Bin'), ('cold_storage', 'Cold Storage'), ('showroom', 'Showroom')], default='warehouse', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about this location')),
                ('code', models.CharField(help_text='Example: WH-01, STR-02, SH-ELEC-01', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.stocklocation')),
            ],
            options={
                'verbose_name': 'Stock Location',
                'verbose_name_plural': 'Stock Locations',
                'db_table': 'stock_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'stock_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='product.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receive', 'Receive'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Positive for incoming, negative for outgoing', max_digits=10)),
                ('reference_type', models.CharField(blank=True, help_text='e.g. purchase_order, order, stock_transfer', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the related record', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='product.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='product.productvariant')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.stocklocation')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Quantity the system believes is in stock', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('counted_quantity', models.DecimalField(decimal_places=2, help_text='Quantity actually counted physically', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('difference', models.DecimalField(decimal_places=2, editable=False, help_text='counted_quantity − system_quantity', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='product.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_lines', to='product.productvariant')),
            ],
            options={
                'db_table': 'stock_count_lines',
                'ordering': ['stock_count', 'product'],
                'indexes': [models.Index(fields=['stock_count'], name='stock_count_stock_c_d608ac_idx'), models.Index(fields=['product'], name='stock_count_product_1b43f6_idx'), models.Index(fields=['variant'], name='stock_count_variant_f3534c_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'product', 'variant'), name='unique_count_line_per_product_variant')],
            },
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['name'], name='stock_locat_name_93223d_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['code'], name='stock_locat_code_51ecbf_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['location_type'], name='stock_locat_locatio_1a0b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['is_active'], name='stock_locat_is_acti_8d2560_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['parent'], name='stock_locat_parent__02e2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['status'], name='stock_count_status_87d2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['location'], name='stock_count_locatio_39b45b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['counted_by'], name='stock_count_counted_0faca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='unique_inventory_per_product_location'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='stock_movem_product_911dad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant'], name='stock_movem_variant_b61577_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location'], name='stock_movem_locatio_b42e22_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_by'], name='stock_movem_created_a0731b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['reference_number'], name='stock_trans_referen_794d48_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status'], name='stock_trans_status_332e43_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_location'], name='stock_trans_from_lo_cccc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_location'], name='stock_trans_to_loca_458feb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['created_by'], name='stock_trans_created_865892_idx'),
        ),
    ]
