# Generated by Django 6.1 on 2026-08-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_inventory'),
        ('product', '0005_alter_product_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='product.product'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
