# Generated by Django 6.1 on 2026-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransfer_product_stocktransfer_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcountline',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='system_quantity',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-filled from Inventory', max_digits=10),
        ),
    ]
