# Generated by Django 6.1 on 2026-08-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockcountline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Main/primary warehouse; new products are saved here automatically.'),
        ),
    ]
