# Generated by Django 6.1 on 2026-08-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_is_default_to_stocklocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stockcount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'ordering': ['id'], 'verbose_name': 'Stock Location', 'verbose_name_plural': 'Stock Locations'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['id']},
        ),
    ]
