# Generated by Django 6.1 on 2026-08-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_alter_stockcount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stockcount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stockcountline',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'ordering': ['-id'], 'verbose_name': 'Stock Location', 'verbose_name_plural': 'Stock Locations'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-id']},
        ),
    ]
